### ISSUE TITLE
Independend Qt5 port and some more changes/fix/improvements

### ISSUE THREAD

**Issue by tobimensch** [lefta/aqemu#1]
Hello,

sadly I've only now seen your Qt 5 port. I recently ported aqemu to Qt5 myself and the repository is at
https://github.com/tobimensch/aqemu .

I'm currently merging changes that are included in your repository but not mine, so that they'll be largely in sync.

I've also fixed a few bugs myself and restructured the project tree to make it clearer. I added a new feature for sharing folders, which works pretty good but I'm probably going to improve it further. Oh and I also added rudimentary support for sending the clipboard over the embedded control window.

And I applied a couple of upstream patches, which you don't seem to have. One is adding support for two sound cards.

I replaced Qt::Xml with a wrapper I created around TinyXML2. It works good and the reason is that Qt::Xml deprecated by the Qt project and shouldn't really be relied on anymore.

Here are some of the changes in my tree:
	* Fixed bug that led to VMs not being terminated when closing the application

	* New feature: Folder sharing

	* New feature: Send clipboard as keys to the VM

	* Fixed bug where SPICE dialog didn't validate correctly.

	* Applied patches for Intel HDA and CS4231A sound suppport (thanks to Eli Carter and others!)

	* Applied patch for fixing SPICE video stream compression support

	* Applied patch that fixes typo

	* Put QDom* TinyXML2 wrapper into its own namespace. Fixes runtime problems in conjunction with KDE.

Do you know what Andrey is doing? Is he still developing aqemu? He seems not be answering mails. In the interest of not duplicating work I suggest working together.

**Comment by lefta** [comment]
Hello,

I'm not maintaining this project, unfortunately I don't have time for this. I switched to virt-manager a while ago, I kept this repo only for sharing purposes; I was sure someone would be interested in it one day or another.

AQemu seems to be the most recent Qt GUI for Qemu, but the latest commit is some years old; it seems abandoned. It doesn't surprise me that the original developper is not responding.

As I said in the Readme, I'm not planning to develop it in any way, but this is a good project which need some love. It is nice that you are working on it, but I can't help you. I already have too much projects and not enough time. If it is OK for you, I will add a link to your repo in the Readme.

**Comment by lefta** [comment]
I see you broke Git history, in general, it is not a good practice. It is better to clone the original, change the remotes and push to the new repository, this way commit history will be kept. Just an advice though.

**Comment by tobimensch** [comment]
You're probably referring to Andrey's repository? I didn't even know that one existed until today. :-) I assumed all that we were left with was a tar blob. And I found patches for it from Fedora and others, so I worked with that thinking I set up the first git repo for aqemu. I see now that wasn't the case, obviously.

**Comment by tobimensch** [comment]
Yes, it would be nice if you would link to my repository. I plan to at least apply patches from other people, if I get any. As you said it's probably the best Qt qemu gui and for me personally it's the best replacement for VirtualBox I found.

virt-manager is also nice, but I found it wasn't friendly towards pure desktop use like VirtualBox and a mess to set up correctly (at least on Fedora) with all its dependencies/config details.

**Comment by lefta** [comment]
Here it is : https://sourceforge.net/p/aqemu/code/ci/master/tree/

It should be possible to apply your commits on top of this.

I did not have any problem with it on my Gentoo, and being on a GTK desktop I prefer having GTK apps when possible.

**Comment by tobimensch** [comment]
> It should be possible to apply your commits on top of this.

I will try it.
